### ISSUE TITLE
[Bug]Invalid regular expression: invalid group specifier name on safari

### ISSUE THREAD

**Issue by ijry** [mdit-plugins/mdit-plugins#26]
### Package name

@mdit/plugin-tab

### Describe the bug

when open in safari it show error Invalid regular expression: invalid group specifier name while all good in chrome.

**Comment by Mister-Hope** [comment]
These plugins are targeting node lts versions, and I am not providing any browser editions.

If you want to import and use it in projects, you should ensure your bundler can inject polyfills correctly
