### ISSUE TITLE
[Bug] Tabs plugins not working in VitePress

### ISSUE THREAD

**Issue by azat-io** [mdit-plugins/mdit-plugins#27]
### Package name

@mdit/plugin-tab

### Describe the bug

<img width="594" alt="image" src="https://user-images.githubusercontent.com/5698350/227788765-9781ca8d-c712-4da5-b61c-14769e54abbc.png">

Renders without `aria-selected` attributes.

Demo:

https://github.com/azat-io/vitepress-mdit-tabs

**Comment by Mister-Hope** [comment]
I don't think there are any bugs here.

Aria attributes are not included because the plug-in do not generate any scripts. Those attributes needs to be extra handled, yet we do not have them in default dom structure.
