### ISSUE TITLE
[Feature Request] Configurable input regex for Include

### ISSUE THREAD

**Issue by jp-diegidio** [mdit-plugins/mdit-plugins#31]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

I'd find it very useful if the input regex (now [`INCLUDE_RE`](https://github.com/mdit-plugins/mdit-plugins/blob/main/packages/include/src/plugin.ts#L43)) in the **Input** plugin was configurable.  The practical problem being that an html comment doesn't show up at all in a standard markdown renderer, nor there is an LSP server here, so I just miss pieces if I view the .md files directly...

### Additional context

This seems a relatively easy extension (as well as without any backwards compatibility issues).  I'd be glad to do it myself and get it to a pull request if helpful.  OTOH, I am quite new to this library and to markdown-it overall: if there is a bigger picture, please feel free to point it out.

**Comment by Mister-Hope** [comment]
I like the idea,  The reason why I choose html comments is that it doesn't appear in the render resulI.

The only problem I think is that how to make sure users are providing of correct regexp pattern for it.  It might be a bit complicated for users.

**Comment by Mister-Hope** [comment]
It's okay for you to just create a PR, make it customizable,  But I hope we can have a little discussion how to lower the regexp knowledge needed.  It would be great if users can customize the syntax easily

**Comment by jp-diegidio** [comment]
> The reason why I choose html comments is that it doesn't appear in the render result.

We must have opposite requirements in that respect, tough I cannot guess where "not seeing it" could be an advantage.

> It might be a bit complicated for users.

I think I see your point, indeed there is no configurable regex or other "complicated thing" across your library at all.

I am seeing essentially two approaches here:

- make that regex configurable (maybe with a warning in the docs that the provided regex is not checked): users are just not compelled to use it, and if they do 1) it's part of the parcel that they should know what they are doing, and 2) normally the regex needed would be a pretty simple one, this is more about "delimiters" (especially since the opening/closing/options as well as the lines/regions handling should indeed stay fixed, only the "body" should be configurable).

- otherwise (here is an idea) just provide two options, one the fixed regex, the other some configurable delimiter...

**Comment by jp-diegidio** [comment]
Hi back, meanwhile I have worked on the idea of just customizable delimiters, taking inspiration from the 'attrs' plugin.

You can see the changes here: <https://github.com/jp-diegidio/mdit-plugins/commit/9df7e658f865a88e9c5b68b3c3264f6576bdd260>

Of course that is just to "make it work": the code anyway needs to be "closed", which I will gladly do if you and everybody is happy with the approach and details (the overall solution but see also my comments in the code for specific details).

I must anticipate that I will have to leave to you or the community extending the documentation and possibly the test cases.

Will look forward to your feedback.

**Comment by jp-diegidio** [comment]
P.S.  I have just realized that I should escape special regexp characters in the left and right options: I will do that across the weekend, doesn't change much as for the overall code...

**Comment by jp-diegidio** [comment]
Well, I do not have all the time in the world, especially for something so simple.  I'll close this issue in two days: I'll just drop the whole thing if you have nothing to add here.

**Comment by Mister-Hope** [comment]
v0.6.4 adds a new option called `useComment`, which should solve your problem.
