### ISSUE TITLE
希望支持一种新的语法来实现选项卡的嵌套

### ISSUE THREAD

**Issue by YiguiDing** [mdit-plugins/mdit-plugins#38]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

语法大概这样，用英文感叹号来标识分栏的分割位置，惊叹号的数量需要和冒号的数量一致，`:::tabs` 对应 `!!!tab`，其实也可以用`@@@tab`指令, 但是感觉在非等宽的字体中，`@`会比`!`看起来要宽一些。

```text

:::tabs

!!!tab 第1栏标题

内容1

!!!tab 第2栏标题

::::::tip 提示

这是内容2，其实主要就是想在选项卡中嵌套提示。

::::::

::::::tabs

!!!!!!tab 第2.1栏标题

内容2.1

!!!!!!tab 第2.2栏标题

内容2.2

::::::

:::

```

**Comment by Mister-Hope** [comment]
我个人其实对象选项卡的嵌套并不持积极态度，这会使得内容变得非常复杂，而且对a11y不友好。

想法是可行的，有兴趣可以自己开发插件实现。

**Comment by Mister-Hope** [comment]
> 这是内容2，其实主要就是想在选项卡中嵌套提示

本身你就可以在选项卡中嵌套其他container

**Comment by YiguiDing** [comment]
我目前好像无法实现在选项卡中嵌套其他container，选项卡似乎把`::::::`当成了它的结束标签

``````md
::: tabs

@tab 分栏标题

:::::: tip

嵌套的提示框

::::::

```ts
function fun() {}
```

:::

``````
![image](https://github.com/mdit-plugins/mdit-plugins/assets/50746494/ab4dd5c2-ec98-4fe4-aa7d-d3c981903270)

**Comment by YiguiDing** [comment]
好的

**Comment by Mister-Hope** [comment]
我的核心拒绝理由是我希望选项卡有简洁的语法，客观点说，你可以用两个不同的 container表达选项卡和选项卡组。

**Comment by YiguiDing** [comment]
好的，明白了，感谢，关闭issues是因为我发现这是我的问题，我误认为选项卡不能嵌套container，实际上是我把嵌套的语法搞错了，嵌套时外层的`:::`应当比内层的多，记错了......
