### ISSUE TITLE
[Feature Request] Add a title containing inline markdown to the block-level custom containers

### ISSUE THREAD

**Issue by AlbertHilb** [mdit-plugins/mdit-plugins#43]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

I'd like to have the possibility to add a title containing inline markdown elements to a custom container block.
Something like

```
::: Theorem **Pythagorean** theorem
Theorem statement 
:::
```

That should be rendered as

```
<div class="Theorem">
<header><b>Pythagorean</b> theorem</header>
<p>Theorem statement</p>
</div>
```

Maybe we can extend the return values allowed for the `validate` configuration parameter, so to include a dictionary containing the string that should be parsed as inline markdown, the name of block the result should be inserted into and the HTML tag to be used to render that block.

In that way, the extension user has the freedom to choose the syntax he wants to adopt.

If you like this idea, I can send a PR implementing this feature.

**Comment by Mister-Hope** [comment]
I think this is totally fine.

**Comment by Mister-Hope** [comment]
This could be easily done by calling `md.renderInline`, see https://github.com/vuepress/ecosystem/pull/274 as an example, so I won't build a new option for this.
