### ISSUE TITLE
[Docs] @mdit/plugin-alert: Missing docs for alert.css import

### ISSUE THREAD

**Issue by mrleblanc101** [mdit-plugins/mdit-plugins#45]
### Package name

@mdit/plugin-alert

### Describe the bug

Should probably mention that there is a `alert.css` file that need to be imported (if you don't want to use custom styles)

### Additional context

I tried `import '@mdit/plugin-alert/alert.css';` but it wasn't working.
I finally figured out by looking at the package.json that it should be `import '@mdit/plugin-alert/style';`.
Either way, both are not documented.

**Comment by mrleblanc101** [comment]
Also, the border-left does not work:
![Screenshot 2024-08-08 at 3 02 26 PM](https://github.com/user-attachments/assets/54d22e80-52fa-41fa-8ea7-51126cc6c970)

I suppose because the declaration use a custom property `border-left: 0.25em solid var(--border-color);`
But the override simply use `border-left-color: #2f81f7;`

If I change `border-left-color: #2f81f7;` to ` --border-color: #2f81f7;`, it works.

**Comment by Mister-Hope** [comment]
![image](https://github.com/user-attachments/assets/cfaa9008-dbd4-4ae9-a2fb-8abba0d4a8ed)

I think this is documented before you open this issue 

Anyway the style issue should be fixed

**Comment by mrleblanc101** [comment]
Oh wow, I see it now, but it's kinda hidden/confusing.
I thought it was part of the demo section since it look so similar.

![Screenshot 2024-09-02 at 12 59 49 PM](https://github.com/user-attachments/assets/003b58d5-8127-4674-b233-e6a037936346)

It would benefit to be moved to the top, maybe right after the [usage](https://mdit-plugins.github.io/alert.html#usage) section since it relates to how to use the plugin.

Here is a quick mockup:
![Screenshot 2024-09-02 at 1 03 54 PM](https://github.com/user-attachments/assets/7b608972-5da0-45f2-92bd-e319bb0ed8f2)

**Comment by Welsh44** [comment]
Hi

Maybe out of subject of this topic. Sorry
You mention to  import '@mdit/plugin-alert/style'
But I don't know and where ...
Can you help me ?
Thanks in advance
