### ISSUE TITLE
[Feature Request] Code copy plugin

### ISSUE THREAD

**Issue by mrleblanc101** [mdit-plugins/mdit-plugins#46]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

All the markdown-it code copy plugins seems outdated, don't support providing custom SVG, only support web hosted iconfont, or don't support showing a "Confirm" status.
It would be nice to have a plugin that work exactly like the Github one.
![2024-08-08 14 47 31](https://github.com/user-attachments/assets/9615841a-f522-488c-b336-5115b6cc3193)

**Comment by Mister-Hope** [comment]
you can take.a look vitepress or @vuepress/plugin-copy-code v2.

There are plenty of plugins that achieve similar thing like you describe

**Comment by mrleblanc101** [comment]
@Mister-Hope Ok, i didn't know about that, thanks.

I will try the Vuepress one.
I searched npmjs with keywords "mardown-it copy" and tested pretty much every single one.

None were complete or working properly. But I did not fall on the Vuepress one with that query.
